### ISSUE TITLE
Error regarding 'caddy reload'

### ISSUE THREAD

**Issue by watzon** [angristan/ansible-caddy#13]
Great project first of all, but for some reason I can't get it to finish. It fails after the "Copy TLS config snippet" task with `ERROR! The requested handler 'caddy reload' was not found in either the main handlers list nor in the listening handlers list`

My playbook:
```yml
- become: true
  hosts: all
  name: Gitea Install

  roles:
    - { role: do1jlr.gitea, tags: gitea }
    - { role: angristan.caddy, tags: caddy }

  vars:
    caddy_src_bin: ../bin/caddy
    caddy_vhosts:
      name: 'gitea'
      hostname: 'git.watzon.tech'
      proxy_host: 'http://localhost:3000'
      gzip: 'compress'
    gitea_fqdn: 'git.watzon.tech'
    gitea_root_url: 'https://git.watzon.tech'
    gitea_protocol: http
    gitea_start_ssh: true
```
